name: Quartz Deploy

on:
  push:
    branches:
      - v4  # Запускать workflow при пуше в ветку v4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}            # IP-адрес твоего сервера
        username: ${{ secrets.USERNAME }}    # Пользователь (root или другой)
        key: ${{ secrets.PRIVATE_KEY }}      # Приватный SSH-ключ
        port: 22
        script: |
          cd ~/Obsidian                       # Переход в директорию проекта
          git pull origin v4                  # Вытягивание последних изменений
          npm install                         # Установка зависимостей
          pkill -f "npx quartz build --serve" || true  # Остановка текущего процесса Quartz (если запущен)
          nohup npx quartz build --serve &    # Запуск Quartz в фоновом режиме

